### ISSUE TITLE
Codeanywhere discount

### ISSUE THREAD

**Issue by petervmeijgaard** [smayzes/awesome-blackfriday#8]
I noticed another discount. Codeanywhere has an -35% off sale on the yearly plans.
I've attached the screenshot below. I was looking on the site for a discount page, but couldn't find any... 😞 
![screen shot 2016-11-24 at 11 23 47 am](https://cloud.githubusercontent.com/assets/5537701/20594994/8b439366-b238-11e6-9470-861316648a67.png)

**Comment by smayzes** [comment]
added :)
